import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")
CALENDLY_API_TOKEN = os.getenv("CALENDLY_API_TOKEN")
CALENDLY_EVENT_TYPE_URI = os.getenv("CALENDLY_EVENT_TYPE_URI")
CALENDLY_PUBLIC_LINK = os.getenv("CALENDLY_PUBLIC_LINK", "https://calendly.com/4davyd0vcreate/30min")
MEETING_TIMEZONE = os.getenv("MEETING_TIMEZONE", "Europe/Moscow")
GOOGLE_SHEETS_API_KEY = os.getenv("GOOGLE_SHEETS_API_KEY")
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv("GOOGLE_SHEETS_SPREADSHEET_ID")
GOOGLE_SHEETS_RANGE = os.getenv("GOOGLE_SHEETS_RANGE", "Content-events!A1:H")
CONTENT_SHEETS_API_KEY = os.getenv("CONTENT_SHEETS_API_KEY", GOOGLE_SHEETS_API_KEY or "")
CONTENT_SHEETS_SPREADSHEET_ID = os.getenv("CONTENT_SHEETS_SPREADSHEET_ID", GOOGLE_SHEETS_SPREADSHEET_ID or "")
CONTENT_SHEETS_RANGE = os.getenv("CONTENT_SHEETS_RANGE", "'Контент-план'!A1:L")
CONTENT_SCHEDULER_TIMEZONE = os.getenv("CONTENT_SCHEDULER_TIMEZONE", "Europe/Moscow")
EXPORT_SHEETS_API_KEY = os.getenv("EXPORT_SHEETS_API_KEY", GOOGLE_SHEETS_API_KEY or "")
EXPORT_SHEETS_BEARER_TOKEN = os.getenv("EXPORT_SHEETS_BEARER_TOKEN", "")
EXPORT_SHEETS_OAUTH_CLIENT_ID = os.getenv("EXPORT_SHEETS_OAUTH_CLIENT_ID", "")
EXPORT_SHEETS_OAUTH_CLIENT_SECRET = os.getenv("EXPORT_SHEETS_OAUTH_CLIENT_SECRET", "")
EXPORT_SHEETS_OAUTH_REFRESH_TOKEN = os.getenv("EXPORT_SHEETS_OAUTH_REFRESH_TOKEN", "")
EXPORT_SHEETS_OAUTH_TOKEN_URL = os.getenv("EXPORT_SHEETS_OAUTH_TOKEN_URL", "https://oauth2.googleapis.com/token")
EXPORT_SHEETS_SPREADSHEET_ID = os.getenv("EXPORT_SHEETS_SPREADSHEET_ID", "")
EXPORT_SHEETS_RANGE = os.getenv("EXPORT_SHEETS_RANGE", "users_export!A1:AB")
EXPORT_SYNC_INTERVAL_MINUTES = int(os.getenv("EXPORT_SYNC_INTERVAL_MINUTES", "5"))

if not BOT_TOKEN:
    raise RuntimeError("BOT_TOKEN не найден в .env")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL не найден в .env")
